# 基本配置
server:
  port: 8080
  servlet:
    context-path: /

# debug模式
debug: false

# spring配置
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  # 彩色终端支持
  output:
    ansi:
      enabled: detect


#MyBatisPlus配置
mybatis-plus:
  # java目录: classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # resource目录: classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/com/mq/rabbitmq/mappers/xmls/**/*.xml
  # 别名包扫描路径
  typeAliasesPackage: com.mq.rabbitmq.domains
  # MyBatis-Plus 全局策略配置
  global-config:
    # DB策略配置
    db-config:
      # 全局默认主键类型 :
      # INPUT 用户输入ID
      # ID_WORKER 全局唯一ID，Long类型的主键
      # ID_WORKER_STR 字符串全局唯一IDs
      # UUID 全局唯一ID，UUID类型的主键
      # NONE 该类型为未设置主键类型
      id-type: AUTO
      # 字段策略
      field-strategy: not_null
      # 表名是否使用下划线命名
      table-underline: true
      #  entity自动生成的 where条件中String类型字段是否使用LIKE
      column-like: false
      # 数据库类型
      db-type: mysql
      # 逻辑已删除值
      logic-delete-value: 1
      # 逻辑未删除值
      logic-not-delete-value: 0

  #原生MyBatis配置
  configuration:
    # 是否开启下划线转驼峰命名规则
    map-underscore-to-camel-case: true
    # 全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存
    # cache-enabled: false
    # 配置JdbcTypeForNull
    jdbc-type-for-null: 'null'

---
# 开发环境
spring:
  profiles: dev

#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/db_springboot?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
#    username: root
#    password: root

  database0:
    url: jdbc:mysql://127.0.0.1:3306/database0?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    databaseName: database0

  database1:
    url: jdbc:mysql://127.0.0.1:3306/database1?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    databaseName: database1

  cache:
    type: redis

  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5000

mybatis-plus:
  configuration:
    cache-enabled: false

logging:
  path: D:\\WorkSpaceJavaLog\\SpringBoot-RabbitMQ\\logs
  file: springboot-rabbitmq-01
  level:
    root: info
    com:
      mq: debug